services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php_apache_container
    volumes:
      - "/c/xampp/htdocs/PDO_MVC_Ecommerce:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html

  mysql:
    image: mysql:8.2
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: phpecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3206:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: