services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php_apache_container
    volumes:
      - "C:/xampp/htdocs/PDO_MVC_Ecommerce:/var/www/html"
    ports:
      - "8081:80"  # PHP Apache accessible at localhost:8081
    depends_on:
      - mysql
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html

  mysql:
    image: mysql:8.2
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: phpecommerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    ports:
      - "3206:3306"   # Map MySQL default port 3306 inside container to 3206 on host
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer_container
    restart: unless-stopped
    ports:
      - "8080:8080"  # Adminer available at localhost:8080

volumes:
  db_data: