services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php_apache_container
    volumes: 
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html

  mysql:
    image: mysql:8.2
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: phpecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    ports:
      - "3206:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: